Changes from yacademy review
newmickymousse/yearn-stargate pull request #12
Opened 2023-01-23 00:30 UTC by simonbdefi

2023-02-07 14:45 UTC, newmickymousse requested changes

2023-02-07 14:45 UTC, newmickymousse commented on interfaces/Stargate/IPool.sol
> -    function totalLiquidity() external view returns (uint256); // the total amount of tokens added on this side of the chain (fees + deposits - withdrawals)
Why remove the comments or meanings of the functions?

2023-02-07 14:45 UTC, newmickymousse commented on tests/Mainnet/test_redeem_local.py
> +    # unstake all lp
I would add an assert to check that balanceOfStakedLPToken > 0

2023-02-07 14:45 UTC, newmickymousse commented on tests/Mainnet/test_redeem_local.py
> +    assert strategy.balanceOfStakedLPToken() == 0
I would add an assert to check that balanceOfUnstakedLPToken > 0

2023-02-07 14:45 UTC, newmickymousse commented on tests/Mainnet/test_redeem_local.py
> +    assert strategy.balanceOfUnstakedLPToken() == 0 # make sure we have transferred all LP tokens using redeemLocal
How long after the redeemLocal does it take to receive the want?

2023-02-07 14:45 UTC, newmickymousse commented on tests/Optimism/test_redeem_local.py
> +import brownie
Please, check other comments in the other test

2023-02-07 19:12 UTC, simonbdefi commented on interfaces/Stargate/IPool.sol
> -    function totalLiquidity() external view returns (uint256); // the total amount of tokens added on this side of the chain (fees + deposits - withdrawals)
reinstated

2023-02-07 19:14 UTC, simonbdefi commented on tests/Mainnet/test_redeem_local.py
> +    # unstake all lp
Changed for both mainnet and opti tests

2023-02-07 19:15 UTC, simonbdefi commented on tests/Mainnet/test_redeem_local.py
> +    assert strategy.balanceOfStakedLPToken() == 0
Changed for both mainnet and opti tests

2023-02-07 19:17 UTC, simonbdefi commented on tests/Optimism/test_redeem_local.py
> +import brownie
done!

2023-02-07 19:44 UTC, simonbdefi commented on tests/Mainnet/test_redeem_local.py
> +    assert strategy.balanceOfUnstakedLPToken() == 0 # make sure we have transferred all LP tokens using redeemLocal
RedeemLocal is block confs of source chain plus block confs of B chain, so less than 1 hour.

2023-02-07 20:51 UTC, simonbdefi commented on tests/Mainnet/test_redeem_local.py
> +    assert strategy.balanceOfUnstakedLPToken() == 0 # make sure we have transferred all LP tokens using redeemLocal
Worst case would be with polygon (512 blocks, about 20 minutes) + other chain (i.e. ETH, about 3-4 min).

2023-02-13 14:24 UTC, simonbdefi commented
Pasting the suggested fix here to have it visible for yacademy who audited Stargate V2,

> > https://github.com/0xValJohn/yearn-stargate/blob/ba019f52473ee739a16072e003b530e1dee606db/contracts/Strategy.sol#L237-L238 Critic! Why only compare the _liquidatedAmount with amountNeeded? You should compare (balanceOfWant() > _liquidatedAmount) >  > 
> > Scenario: >  amountNeeded = 10 preWithdrawnWant = 8 balanceOfAllLPTokenStakedInWant = 8 balanceOfAllLPTokenIdleInWant = 0
> > Now you liquidated 2 from balanceOfAllLPTokenStakedInWant now: >  >  balanceOfWant() = 10  > balanceOfAllLPTokenStakedInWant = 6
> > When you come to this line you’ll do this: > 10>2 ? Go inside if  > balanceOfLPTokens = 6 potentialLoss = 10-2 = 8
> > Loss = 8 > 6 ? 8-6 : 0 Which loss = 2 Although we have the want needed in the first place.
> 
Suggest the following:
 
 ```solidity
 if (_amountNeeded > _balanceOfWant) {
     uint256 balanceOfLPTokens = _lpToLd(balanceOfAllLPToken());
     uint256 _potentialLoss = _amountNeeded - _liquidatedAmount;
     unchecked {
         _loss = _potentialLoss > balanceOfLPTokens ? _potentialLoss - balanceOfLPTokens : 0;
     }
 }
 ```
 
 Would like to get vetting from all you 3 reviewers (@mil0xeth @tapired @newmickymousse) as this function is critical.

2023-02-23 20:13 UTC, closed without merging