feat: fix debtRepayment issue in Strategy.sol, tests for CMO migration
newmickymousse/yearn-stargate pull request #8
Opened 2022-11-03 21:08 UTC by mil0xeth

- fix debtRepayment issue in Strategy.sol 
- tests for CMO migration

2022-11-03 23:30 UTC, mil0xeth commented
![strategychanges](https://user-images.githubusercontent.com/96582887/199854279-82354795-8b96-48a7-81d4-23b37f2820da.png)
changes to the strategy

2022-11-04 01:24 UTC, newmickymousse requested changes

2022-11-04 01:24 UTC, newmickymousse commented on tests/Mainnet/test_0cmo.py
> +    new_stargate_usdt = strategist.deploy(Strategy, usdt_vault, lp_staker, 1, False, True, "StargateV2-USDC")
name should be "StargateV2-USDT"

2022-11-04 01:24 UTC, newmickymousse commented on tests/Mainnet/test_delta_credit.py
> +    tx = strategy.harvest({"from": gov})
we should add an assert that there are no losses and there is still a debtOutstanding.. `assert vault.debtOutsanding(strategy) > 0`. This basically confirms that there is still debt in the strategy that we couldn't withdraw yet.

2022-11-04 10:26 UTC, mil0xeth commented on tests/Mainnet/test_0cmo.py
> +    new_stargate_usdt = strategist.deploy(Strategy, usdt_vault, lp_staker, 1, False, True, "StargateV2-USDC")
done

2022-11-04 10:26 UTC, mil0xeth commented on tests/Mainnet/test_delta_credit.py
> +    tx = strategy.harvest({"from": gov})
done

2022-11-04 10:52 UTC, newmickymousse approved these changes

2022-11-04 10:53 UTC, merged